force-app/main/default/objects/MyOrgButler__c/MyOrgButler__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>My Org Butler</label>
</CustomObject>

force-app/main/default/objects/MyOrgButler__c/fields/TavilyApiKey__c.field-meta.xml
<CustomField>
    <fullName>TavilyApiKey__c</fullName>
    <label>Tavily API Key</label>
    <description>API Key for Tavily Search</description>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tools/SearchWebTool_Test.cls
@IsTest
private class SearchWebTool_Test {
    
    @IsTest
    private static void happyPath() {

        // Setup
        insert new MyOrgButler__c(TavilyApiKey__c = '123');

        SearchWeb.Answer expected = answerWith('Donald Trump was elected in November 2024.');
        new HttpMock()
                .post('/search', expected)
                .mock();

        // Exercise
        Test.startTest();
        String response = new SearchWebTool().execute('{ "query" : "Who is the 47th US president?" }');
        Test.stopTest();

        // Verify
        SearchWeb.Answer actual = (SearchWeb.Answer) JSON.deserialize(response, SearchWeb.Answer.class);
        System.assertEquals(expected.answer, actual.answer);
    }

    // HELPER

    private static SearchWeb.Answer answerWith(String content) {
        SearchWeb.Answer result = new SearchWeb.Answer();
        result.answer = content;
        return result;
    }
}